name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 lint
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --ignore=E302,E305,W292,E402

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Build Docker image
        run: docker build -t ml-api .

        # 7. Login to DockerHub (secure)
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8. Tag Docker image
      - name: Tag Docker image
        run: docker tag ml-api ${{ secrets.DOCKER_USERNAME }}/ml-api:latest

      # 9. Push to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ml-api:latest